if filereadable(expand("~/.vimrc.bundles"))
  source ~/.vimrc.bundles
endif

set nu
set showcmd
set laststatus=1
set showmatch
set matchtime=1
set nobackup
set autoindent
set confirm

set tabstop=4
set shiftwidth=4
set smarttab
set nocompatible
set expandtab

set wildmenu
set fo=cqrt
set laststatus=2
set textwidth=78
set ww=<,>,h,l
set noeb visualbell
let mapleader = ","

filetype on
filetype plugin on
filetype indent on
syntax on
syntax enable

set fencs=utf-8,usc-bom,shift-jis,gb18030,gbk,gb2312,cp936
set termencoding=utf-8
set encoding=utf-8
set fileencodings=ucs-bom,utf-8,cp936
set fileencoding=utf-8
